### ISSUE TITLE
Quest: Shutting Down Manaforge B'naar

### ISSUE THREAD

**Issue by Cofic** [Warcrusade/Bugtracker#1]
**Description:**

Bug during Quest: "Shutting Down Manaforge B'naar" . After getting the Access crystal and trying to use it on the console to shut it down. I get instantly disconnected and unable to connect to server for 5-10seconds. Unable to progress quest further. The quest worked fine on beta couple months back.

**Current behaviour:**

**Expected behaviour:**

The console should begin to shut down. And mobs are supposed to spawn in small waves for a certain period of time. Before the console is completely shut down.

**Steps to reproduce the problem:**

1. Get the quest in Netherstorm, get the access crystal from overseer.
2. Use the console and try to shut it down.
3. You will get disconnected.

**Comment by TeronDev** [comment]
Fixed
