### ISSUE TITLE
Can't summon Nightbane

### ISSUE THREAD

**Issue by symrzknr** [Warcrusade/Bugtracker#14]
**Description:**

When you click the Blackened Urn at the Master's Terrace, Nightbane does not show up.

**Current behaviour:**

In our Karazhan save every boss is dead excepting Terestian and Netherspite. After completing the preQ and using the urn at the Terrace, can't summon Nightbane.

**Expected behaviour:**

Use the urn and summon Nightbane.

**Steps to reproduce the problem:**

1. Do Nightbane's preQ at Karazhan
2, Go to the Terrace with the Blackened Urn and click it.
3. Nothing happens
4. Altf4 and relog = critical wow error
5. Log in again, you appear at Kz's door and cant zone in: "Unable to zone in while an encounter is in progress"
6. Your Karazhan ID blocked for the rest of the save

**Comment by TeronDev** [comment]
Thanks for reporting, it got bugged with a recent cmangos update. I'll apply the fix tomorrow on live.
