### ISSUE TITLE
Profession vendors in the mall are missing items.

### ISSUE THREAD

**Issue by kvasir-jotner** [Warcrusade/Bugtracker#2]
**Description:**

Profession trainers / Vendors in the mall does not carry the necessary items for leveling said profession. 
Leveled LW yesterday and the vendor did not have salts or threads like the normal profession vendor in Orgrimmar (or any other location) have.

**Current behaviour:**
Missing important reagents.

**Expected behaviour:**
Should carry the same reagents as normal profession vendors.

**Steps to reproduce the problem:**

1. Go to LW profession trainer in mall
2. Open store under the train me option. 
3. See that a lot of reagents are missing.

**Comment by TeronDev** [comment]
Not a bug
