### ISSUE TITLE
Can't complete Old Hillsbrad Foothills (CoT1)

### ISSUE THREAD

**Issue by symrzknr** [Warcrusade/Bugtracker#5]
**Description:**

Thrall gets bugged before last boss (Epoch Hunter) and event freezes.

**Current behaviour:**

The last pull of mobs before the last boss is inside a house, where Thrall finds Taretha. At this point, the human mobs spawn but disappear so you don't have the chance to kill them.

Then you speak with Taretha to carry on with the event, Epoch Hunter is called and comes forth outside the house. This boss has got 3 adds. Only 1 of the adds is hostile, and after killing it the event gots frozen without nothing happening.

**Expected behaviour:**

The before mentioned last pull should be normal, killing the mobs. Then after speaking with Taretha all 3 adds of Epoch Hunter should be hostile and after killing them the boss should be engaged.

**Steps to reproduce the problem:**

1. Go to CoT 
2. Make PreQ
3. Get in OHF
4. Start Thrall's event after killing 1st boss
5. Follow Thrall until last pull and see adds disappear before fighting.
6. Speak with Taretha
7. Kill 1st Epoch Hunter add and event gots frozen.

**Comment by kvasir-jotner** [comment]
Currently at the same stage with the same bug.
