### ISSUE TITLE
Drop rate on mote of earth

### ISSUE THREAD

**Issue by kvasir-jotner** [Warcrusade/Bugtracker#9]
**Description:**
The issue i'm having is that leatherworkers need a lot of https://www.wowhead.com/item=22573/mote-of-earth to turn into https://www.wowhead.com/item=22452/primal-earth. 

Some mobs that are supposed to drop these don't ( https://www.wowhead.com/npc=17157/shattered-rumbler ) 
They should have a 18% drop rate.

Some Others do, and should have about 20% droprate but it's more like maximum 8%. (https://www.wowhead.com/npc=18882/sundered-thunderer)
 Spent 2 hours yesterday farming them and got like 1 primal earth in the end. 

**Current behaviour:**
To low to non-existent drop-rate for items that is needed for high level professions.

**Expected behaviour:**
Should drop according to stats on wow-head, preferably higher.

**Steps to reproduce the problem:**

1. Farm above mobs over a longer time span, cry a little.
2. Continue farming.
3. Hope

**Comment by kvasir-jotner** [comment]
RE this issue, i see others in discord are also mentioning very low drop-rates, 
I thins boosting those numbers quite a bit might be a good decision and will help the server grow.

It's a fun server after all<3

**Comment by TeronDev** [comment]
The drop rates are blizzlike and working as intended.

**Comment by Cuttingedge79** [comment]
Drop rates are horrid. Be them blizzlike or not.
